name: dicoding_food_deli
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  getwidget: ^4.0.0
  http: ^1.2.0
  provider: ^6.1.1
  sqflite: ^2.3.2
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.2
  rxdart: ^0.27.7
  android_alarm_manager_plus: ^3.0.4
  http_mock_adapter: ^0.6.1

flutter_native_splash:
  color: "#fec7bd"
  # background_image: assets/img/bg-splash.png
  image: assets/img/splash/logo-splash-12.png
  android_12:
    color: "#fec7bd"
    image: assets/img/splash/logo-splash-12.png
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
  sqflite_common_ffi: ^2.3.2+1

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/logo/
    - assets/img/merchant_item/
    - assets/img/splash/
